services:
  redis:
    image: redis:7.2-alpine
    # Uncomment the following lines to expose Redis port for debugging
    #ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  forbidden-sector:
    build: .
    ports:
      - "9082:9082"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn server:app --host 0.0.0.0 --port 9082 --reload
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data: